kind: pipeline
type: docker
name: default

steps:
- name: build
  image: golang
  environment:
    GOOS: linux
    GOARCH: amd64
    CGO_ENABLED: "0"
  commands:
  - go build -o bdc-drone-discord

- name: docker-registry
  image: plugins/docker
  network_mode: bridge
  settings:
    repo: brazildatacube/bdc-drone-discord
    username:
      from_secret: dockerhub_user
    password:
      from_secret: dockerhub_pass
    auto_tag: true
  when:
    event:
      - push
      - tag

- name: discord-notify
  image: brazildatacube/bdc-drone-discord
  settings:
    webhook:
      from_secret: discord_webhook
  when:
    status:
      - failure
      - success
